- .github/workflows/_release.yml
This PR adds a Neo4j service to the `_release.yml` workflow and removes unneeded environment variables from the integration tests step.
> Adds a Neo4j service to release workflow

- .gitignore
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/tests/integration_tests/vectorstores/test_neo4jvector.py
- libs/neo4j/tests/unit_tests/vectorstores/test_neo4j.py
The previous Cypher query would include a warning that the Cypher query will be deprecated. This PR update the query to have a variable scope clause. See https://neo4j.com/docs/cypher-manual/current/subqueries/call-subquery/#variable-scope-clause
This PR also adds a unit test and was manually tested.
> Include variable scope clause in deprecated Cypher query

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/graphs/neo4j_graph.py
- libs/neo4j/tests/integration_tests/graphs/test_neo4j.py
- libs/neo4j/tests/unit_tests/graphs/test_neo4j_graph.py
From [neo4j driver](https://github.com/neo4j/neo4j-python-driver/blob/5.0/src/neo4j/_sync/driver.py#L535-L554) impl: 
def __del__(
self,
_unclosed_resource_warn=unclosed_resource_warn,
_is_async_code=Util.is_async_code,
_deprecation_warn=deprecation_warn,
):
if not self._closed:
_unclosed_resource_warn(self)
if _is_async_code:
return
if not self._closed:
_deprecation_warn(
"Relying on Driver's destructor to close the session "
"is deprecated. Please make sure to close the session. "
"Use it as a context (`with` statement) or make sure to "
"call `.close()` explicitly. Future versions of the "
"driver will not close drivers automatically."
)
self.close()
>
>
We're currently relying on the driver destructor/python garbage collection. This PR adds basic context management which:
- enables …
> feat: add driver connection lifecycle mgmt to adhere to neo4j Driver expectations

- libs/neo4j/tests/integration_tests/chains/test_graph_database.py
Removes the `test_cypher_save_load` test from the `GraphCypherQAChain` integration tests.
Low
> Removes the test_cypher_save_load test from the GraphCypherQAChain integration tests

- .gitignore
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/poetry.lock
- libs/neo4j/pyproject.toml
- libs/neo4j/tests/unit_tests/vectorstores/test_neo4j.py
This PR improves test coverage for `neo4j_vector.py` from 84% to 97%.
For the unit tests, a fixture `neo4j_vector_factory` was added to avoid repeated code when setting up unit tests.
Medium
> Added new tests to improve test coverage for Neo4jVector

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/chains/graph_qa/cypher.py
- libs/neo4j/tests/integration_tests/chains/test_graph_database.py
- libs/neo4j/tests/unit_tests/chains/test_graph_qa.py
- libs/neo4j/tests/unit_tests/llms/fake_llm.py
This PR removes the deprecated `LLMChain` class from the `GraphCypherQAChain`. This fixes the bug which is caused when instantiating the `GraphCypherQAChain` with the `use_function_response` parameter.
Medium
> Removes LLMChain from GraphCypherQAChain

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/chains/graph_qa/cypher.py
- libs/neo4j/langchain_neo4j/graphs/neo4j_graph.py
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/tests/integration_tests/graphs/test_neo4j.py
- libs/neo4j/tests/unit_tests/graphs/test_neo4j_graph.py
- libs/neo4j/tests/unit_tests/vectorstores/test_neo4j.py
This PR updates type information to remove all but 3 `#type: ignore` comments.
Medium
> Removes `#type: ignore` comments

- libs/neo4j/tests/integration_tests/chat_message_histories/test_neo4j.py
- libs/neo4j/tests/unit_tests/chat_message_histories/test_neo4j_chat_message_history.py
Adds tests so that Neo4jChatMessageHistory class now has 100% coverage
Medium
- [] CHANGELOG.md updated
> Adds tests so that Neo4jChatMessageHistory class now has 100% coverage

- libs/neo4j/langchain_neo4j/graphs/neo4j_graph.py
- libs/neo4j/tests/integration_tests/graphs/test_neo4j.py
- libs/neo4j/tests/unit_tests/graphs/test_neo4j_graph.py
Adds tests so that `Neo4jGraph` class now has 100% coverage
Medium
> Adds tests so that Neo4jGraph class now has 100% coverage

- libs/neo4j/poetry.lock
- libs/neo4j/pyproject.toml
Moves LangChain core dependency to 0.3.8
Low
> Moved LangChain core to 0.3.8

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/graphs/graph_document.py
- libs/neo4j/langchain_neo4j/graphs/neo4j_graph.py
- libs/neo4j/tests/unit_tests/graphs/test_neo4j_graph.py
This PR updates the `GraphDocument` class to make the `source` parameter optional. It also updates the `add_graph_documents` method of the `Neo4jGraph` class to work with this. This is to allow users to add nodes and relationships to a graph without the need for a source document.
Low
> Makes the source parameter of GraphDocument optional

- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/tests/unit_tests/vectorstores/test_neo4j.py
From [this issue](https://github.com/langchain-ai/langchain-neo4j/issues/30).
When loading an existing index via Neo4jVector.from_existing_index(), a singleton of Neo4jVector is created, which in init calls [the embedding model to find the number of embedding dimensions.](https://github.com/langchain-ai/langchain-neo4j/blob/a6c8e139aa4beb505cb79c446a72d0c53a28e7ef/libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py#L597).
This call to the embedding model is a headache in CICD, where you do not want to and can not call third-party embedding services during integration tests.
Low
> Provide optional parameter for embedding dimension in Neo4jVector

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/graphs/neo4j_graph.py
- libs/neo4j/tests/unit_tests/graphs/test_neo4j_graph.py
This PR fixes a few issues with the enhanced schema function of the `Neo4jGraph` class:
- Updates the `schema_counts` query to use the `apoc.meta.graph` procedure rather than the `apoc.meta.graphSample` procedure, which isn't as accurate.
- Removes the previously added default setting suppressing all warnings from the Neo4j driver.
- Adds `session_params` parameter to the `query` method of `Neo4jGraph` allowing for the passing of session specific parameters to the Neo4j driver.
- Updates the `Neo4jGraph.query` call used to get the enhanced schema so that specific warnings raised by this call are suppressed.
Medium
> Enhanced schema fixes

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/graphs/graph_store.py
- libs/neo4j/tests/unit_tests/chains/test_graph_qa.py
Previously, the `GraphStore` abstract base class lived in the LangChain Community package, allowing other graph DB vendors to inherit from it and build integrations for LangChain. We have now moved this class to the LangChain Neo4j package. We also require the `graph` passed to the `GraphCypherQAChain` to be a `GraphStore`. This means that other graph DB vendors must now inherit from the `GraphStore` class in the LangChain Neo4j package in order to be compatible with the `GraphCypherQAChain`.
This PR changes the `GraphStore` class to a [Protocol](https://mypy.readthedocs.io/en/stable/protocols.html), which allows other graph integrations to work with the `GraphCypherQAChain` without the explicit need to inherit from the `GraphStore` class in the LangChain Neo4j package.
Low
> Makes GraphStore a Protocol

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/graphs/graph_store.py
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/tests/unit_tests/vectorstores/test_neo4j.py
Adds the `/` character to the list of characters to be escaped before sending a query to Apache Lucene.
See [list of special characters](https://lucene.apache.org/core/10_1_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#escaping-special-characters-heading)
Low
> Added missing lucene special char to remove_lucene_chars

- libs/neo4j/langchain_neo4j/chat_message_histories/neo4j.py
- libs/neo4j/tests/integration_tests/chat_message_histories/test_neo4j.py
- Refactors `Neo4jChatMessageHistory` to use Cypher queries from the neo4j-graphrag package.
- Renames the `type` property to `role` on `Message` nodes saved by the `Neo4jChatMessageHistory` class. 
- Adds a `delete_session_node` parameter to `Neo4jChatMessageHistory`'s `clear` method allowing developers to optionally select if they want to delete the `Session` node along with all `Message` nodes in a chat message chain.
Low
> Updates Neo4jChatMessageHistory to use neo4j-graphrag queries

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/chat_message_histories/neo4j.py
- libs/neo4j/langchain_neo4j/graphs/neo4j_graph.py
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/tests/integration_tests/chains/test_graph_database.py
- libs/neo4j/tests/integration_tests/chat_message_histories/test_neo4j.py
- libs/neo4j/tests/integration_tests/conftest.py
- libs/neo4j/tests/integration_tests/graphs/test_neo4j.py
- libs/neo4j/tests/integration_tests/utils.py
- libs/neo4j/tests/integration_tests/vectorstores/test_neo4jvector.py
- libs/neo4j/tests/unit_tests/chat_message_histories/test_neo4j_chat_message_history.py
- libs/neo4j/tests/unit_tests/graphs/test_neo4j_graph.py
- libs/neo4j/tests/unit_tests/vectorstores/test_neo4j.py
- Removes unneeded `try: import neo4j` statements.
- Removes tests which test for errors raised when these statements fail.
- Adds `clear_neo4j_database` and `neo4j_credentials` fixtures to the integration tests streamlining handling of database credentials in these tests and making them less flaky.
- Updates integration tests to use these fixtures.
Low
> Removes unneeded ImportErrors

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/chains/graph_qa/cypher.py
- libs/neo4j/tests/integration_tests/chains/test_graph_database.py
- libs/neo4j/tests/unit_tests/chains/test_graph_qa.py
- Removes the `extract_cypher` function and associated tests and replaces it with the `extract_cypher` function from the Neo4j GraphRAG package.
- Updates the `GraphCypherQAChain` to use the same schema format as `Neo4jGraph`.
- Updates the `construct_schema` function used by the `GraphCypherQAChain` to use schema creation functions from the Neo4jGraph GraphRAG package.
Low
> Refactors GraphCypherQAChain with Neo4j GraphRAG code

- libs/neo4j/langchain_neo4j/chains/graph_qa/cypher_utils.py
- libs/neo4j/tests/unit_tests/chains/test_cypher_utils.py
This PR fixes the `extract_paths` method of the `CypherQueryCorrector`. Previously this function would enter into an infinite loop whenever there was a repeated path in a Cypher query. Unit tests have also been added to test the `CypherQueryCorrector`.
Low
> Fixes extract_paths infinite loop

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/chains/graph_qa/cypher.py
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/tests/integration_tests/graphs/test_neo4j.py
- libs/neo4j/tests/integration_tests/vectorstores/test_neo4jvector.py
- libs/neo4j/tests/unit_tests/chains/test_graph_qa.py
- libs/neo4j/tests/unit_tests/vectorstores/test_neo4j.py
Reverts langchain-ai/langchain-neo4j#51 due to issues identified during further testing. The changes did not work as expected and required users to provide a chat_history, which should not be mandatory.
Moreover, the currently recommended approach for managing message history is through [LangGraph persistence](https://python.langchain.com/docs/how_to/message_history/), making this change unnecessary.
> Revert "FIX: Added 'chat_history' as an argument to the self.qa_chain.invoke() in GraphCypherQAChain"

- .github/workflows/_release.yml
- libs/neo4j/langchain_neo4j/chat_message_histories/neo4j.py
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/tests/integration_tests/chat_message_histories/test_neo4j.py
- libs/neo4j/tests/integration_tests/conftest.py
- libs/neo4j/tests/integration_tests/docker-compose/neo4j.yml
- Gives developers the ability to use custom DBs with Neo4jChatMessageHistory
- Adds an integration test for the above
- Changes the default password for the integration tests Neo4j Docker container from `pleaseletmein` to `password`
- Updates the version of Neo4j used by the integration tests from neo4j:5.24 to neo4j:5.24.2-enterprise
Low
> Neo4jChatMessageHistory custom DBs

- CHANGELOG.md
- libs/neo4j/langchain_neo4j/vectorstores/neo4j_vector.py
- libs/neo4j/poetry.lock
- libs/neo4j/pyproject.toml
Release 0.5.0. Fixes several bugs. Updates the `neo4j-graphrag` dependency to version 1.9.0. 
Fixes:
- https://github.com/langchain-ai/langchain-neo4j/issues/56
- https://github.com/langchain-ai/langchain-neo4j/issues/62
- https://github.com/langchain-ai/langchain-neo4j/issues/70
Low
> Release 0.5.0

- libs/neo4j/poetry.lock
- libs/neo4j/pyproject.toml
The [0.5.0 release workflow](https://github.com/langchain-ai/langchain-neo4j/actions/runs/16518623800/job/46715131584) was failing. The cause of this was a [Pydantic issue](https://github.com/langchain-ai/langchain/pull/29963) in `langchain-core`. This was fixed in [version 0.3.39](https://github.com/langchain-ai/langchain/releases/tag/langchain-core%3D%3D0.3.39). This PR updates the `langchain-core` dependency with this fix.
Low
> Bumps langchain-core patch version
